# This is an example of environment-specific configuration file, the
# build script should copy the right one to the build directory.

acl:
  # https://github.com/alphagov/govuk-cdn-config/blob/master/vcl_templates/www.vcl.erb#L148
  fastlypurge:
    # generic
  - "37.26.93.252/32"   # Skyscape mirrors
  - "31.210.241.100/32" # Carrenza mirrors
  - "23.235.32.0/20"    # Fastly cache node
  - "43.249.72.0/22"    # Fastly cache node
  - "103.244.50.0/24"   # Fastly cache node
  - "103.245.222.0/23"  # Fastly cache node
  - "103.245.224.0/24"  # Fastly cache node
  - "104.156.80.0/20"   # Fastly cache node
  - "151.101.0.0/16"    # Fastly cache node
  - "157.52.64.0/18"    # Fastly cache node
  - "172.111.64.0/18"   # Fastly cache node
  - "185.31.16.0/22"    # Fastly cache node
  - "199.27.72.0/21"    # Fastly cache node
  - "199.232.0.0/16"    # Fastly cache node
  - "202.21.128.0/24"   # Fastly cache node
  - "203.57.145.0/24"   # Fastly cache node
  - "167.82.0.0/17"     # Fastly cache node
  - "167.82.128.0/20"   # Fastly cache node
  - "167.82.160.0/20"   # Fastly cache node
  - "167.82.224.0/20"   # Fastly cache node
  # integration (assuming this is the config file for integration)
  - "34.248.229.46/32"  # AWS Integration NAT gateway
  - "34.248.44.175/32"  # AWS Integration NAT gateway
  - "52.51.97.232/32"   # AWS Integration NAT gateway
  # https://github.com/alphagov/govuk-cdn-config/blob/master/vcl_templates/www.vcl.erb#L201
  allowlist: []
