# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["Michael Walker (barrucadu) <mike@barrucadu.co.uk>"]
description = "Demo Compute@Edge project using Rust"
language = "rust"
manifest_version = 1
name = "rust"
service_id = ""

[local_server]
  [local_server.backends]
    [local_server.backends.origin]
      url = "http://127.0.0.1:8888/"
    [local_server.backends.mirrorS3]
      url = "http://127.0.0.1:8889/"
    [local_server.backends.mirrorS3Replica]
      url = "http://127.0.0.1:8890/"
    [local_server.backends.mirrorGCS]
      url = "http://127.0.0.1:8891/"
